-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, SUM(D.SALES*C.PRICE) AS TOTAL_SALES
FROM BOOK_SALES D
JOIN 
(SELECT A.AUTHOR_ID, A.BOOK_ID, A.PRICE, A.CATEGORY, B.AUTHOR_NAME
FROM BOOK A
JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID) AS C
ON D.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE LIKE '2022-01-%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC

# SELECT A.AUTHOR_ID, A.BOOK_ID, A.PRICE, A.CATEGORY, B.AUTHOR_NAME
# FROM BOOK A
# JOIN AUTHOR B
# ON A.AUTHOR_ID = B.AUTHOR_ID