# -- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM
(SELECT *
FROM FOOD_PRODUCT
GROUP BY CATEGORY, PRODUCT_NAME
HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC) B
GROUP BY CATEGORY
# HAVING MAX(PRICE)
ORDER BY PRICE DESC

# SELECT *
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# # # # GROUP BY CATEGORY

# (SELECT *
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY)

# 마조유, 김치찌개, 허니버터칩, 배추김치